org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8
org.gradle.configuration-cache=true
org.gradle.caching=true
org.gradle.parallel=true
kotlin.code.style=official

pluginGroup=com.zaycev.libshelper
pluginName=LibsHelper
pluginId=com.zaycev.libshelper
pluginVersion=1.1.0
pluginSinceBuild=261
pluginVendorName=Anton Zaycev
pluginVendorEmail=ya.antonio19@gmail.com
pluginVendorUrl=https://github.com/Anton-Zaitsev/LibsHelperPlugin
intellijPlatformPublishingToken=

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
