[versions]
kotlin = "2.4.20"
intellij-platform = "2.18.1"
intellij-idea = "2025.2.5"
foojay-resolver = "1.0.0"
junit-jupiter = "5.13.4"
jvm = "21"
gradle = "9.7.1"
coroutines = "1.11.0"
serialization = "1.11.0"
collections-immutable = "0.5.2"
metro = "1.4.2"
detekt = "2.0.0-alpha.6"
composeRules = "0.6.6"

[libraries]
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "collections-immutable" }
gradleplugins-detekt = { module = "dev.detekt:detekt-gradle-plugin", version.ref = "detekt" }
detekt-api = { module = "dev.detekt:detekt-api", version.ref = "detekt" }
detekt-test = { module = "dev.detekt:detekt-test", version.ref = "detekt" }
detekt-test-assertj = { module = "dev.detekt:detekt-test-assertj", version.ref = "detekt" }
detekt-ktlint-wrapper = { module = "dev.detekt:detekt-rules-ktlint-wrapper", version.ref = "detekt" }
detekt-compose = { module = "io.nlopez.compose.rules:detekt", version.ref = "composeRules" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
intellij-platform = { id = "org.jetbrains.intellij.platform", version.ref = "intellij-platform" }
intellij-platform-settings = { id = "org.jetbrains.intellij.platform.settings", version.ref = "intellij-platform" }
foojay-resolver = { id = "org.gradle.toolchains.foojay-resolver-convention", version.ref = "foojay-resolver" }
metro = { id = "dev.zacsweers.metro", version.ref = "metro" }
detekt = { id = "dev.detekt", version.ref = "detekt" }
